"""TypeScript MCP server generation from normalized operations."""

from __future__ import annotations

from dataclasses import dataclass
import itertools
from functools import lru_cache
from pathlib import Path
import re
from typing import Any, TypeAlias

from jinja2 import Environment, FileSystemLoader

from mcp_toolsmith.models import OperationModel, ParameterModel, SchemaModel
from mcp_toolsmith.scorer import ScoringResult

_UNSAFE_METHODS = {"delete", "put", "patch"}
_TEMPLATE_DIR = Path(__file__).with_name("templates")
_IDENTIFIER_PATTERN = re.compile(r"[^a-zA-Z0-9_]")
# TypeScript identifier: must start with a letter or underscore
_TS_IDENTIFIER_RE = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_]*$")

OperationDict: TypeAlias = dict[str, Any]


@dataclass(frozen=True)
class GenerationResult:
    """Summary of generated and skipped output."""

    files: list[Path]
    skipped_operations: list[str]


@dataclass(frozen=True)
class _GroupedOperations:
    module_name: str
    tag: str
    operations: list[OperationDict]


def group_by_tag(ops: list[OperationModel]) -> dict[str, list[OperationModel]]:
    """Group operations by their first tag, falling back to ``default``."""

    grouped: dict[str, list[OperationModel]] = {}
    for op in ops:
        key = op.tags[0] if op.tags else "default"
        grouped.setdefault(key, []).append(op)
    return grouped


def generate(
    ops: list[OperationModel],
    score_result: ScoringResult,
    out_dir: Path | str,
    dry_run: bool = False,
    unsafe: bool = False,
) -> GenerationResult:
    """Render a TypeScript MCP server project for the eligible operations.

    Args:
        ops: All extracted operations from the OpenAPI spec.
        score_result: Scoring metadata; passed through to templates as context.
        out_dir: Root directory for the generated project.
        dry_run: When True, return the planned file list without writing anything.
        unsafe: When True, include DELETE/PUT/PATCH operations that are skipped
            by default.

    Returns:
        A :class:`GenerationResult` describing written (or planned) files and
        the operation IDs that were skipped.
    """
    destination = Path(out_dir)
    skipped_operations = sorted(
        op.operation_id for op in ops if not unsafe and op.http_method in _UNSAFE_METHODS
    )
    included_operations = [
        op for op in ops if unsafe or op.http_method not in _UNSAFE_METHODS
    ]

    env = _template_environment()
    grouped_context = _build_grouped_context(included_operations)
    planned_files = [
        destination / "src" / "index.ts",
        destination / "src" / "config.ts",
        destination / "package.json",
        destination / "tsconfig.json",
    ] + [destination / "src" / "tools" / f"{group.module_name}.ts" for group in grouped_context]

    if dry_run:
        return GenerationResult(files=planned_files, skipped_operations=skipped_operations)

    for path in planned_files:
        path.parent.mkdir(parents=True, exist_ok=True)

    context: dict[str, Any] = {
        "groups": grouped_context,
        "score": score_result,
        "generated_at": "generated by mcp-toolsmith",
    }
    (destination / "src" / "index.ts").write_text(
        env.get_template("index.ts.j2").render(**context), encoding="utf-8"
    )
    (destination / "src" / "config.ts").write_text(
        env.get_template("config.ts.j2").render(**context), encoding="utf-8"
    )
    (destination / "package.json").write_text(
        env.get_template("package.json.j2").render(**context), encoding="utf-8"
    )
    (destination / "tsconfig.json").write_text(
        env.get_template("tsconfig.json.j2").render(**context), encoding="utf-8"
    )

    tool_template = env.get_template("tool_module.ts.j2")
    for group in grouped_context:
        (destination / "src" / "tools" / f"{group.module_name}.ts").write_text(
            tool_template.render(group=group, **context), encoding="utf-8"
        )

    return GenerationResult(files=planned_files, skipped_operations=skipped_operations)


@lru_cache(maxsize=1)
def _template_environment() -> Environment:
    """Return a cached Jinja2 environment pointing at the bundled templates."""
    env = Environment(
        loader=FileSystemLoader(str(_TEMPLATE_DIR)),
        trim_blocks=True,
        lstrip_blocks=True,
    )
    env.filters["json_schema"] = _json_schema
    return env


def _build_grouped_context(ops: list[OperationModel]) -> list[_GroupedOperations]:
    """Build a sorted list of tag-grouped operation contexts for template rendering."""
    groups: list[_GroupedOperations] = []
    grouped = group_by_tag(ops)
    for tag, tag_ops in sorted(grouped.items()):
        module_name = _sanitize_identifier(tag)
        groups.append(
            _GroupedOperations(
                module_name=module_name,
                tag=tag,
                operations=[
                    _operation_context(op)
                    for op in sorted(tag_ops, key=lambda item: item.operation_id)
                ],
            )
        )
    return groups


def _operation_context(op: OperationModel) -> OperationDict:
    """Convert an :class:`OperationModel` into a plain dict for Jinja2 rendering."""
    return {
        "operation_id": op.operation_id,
        "summary": op.summary or op.description or f"Call {op.http_method.upper()} {op.source_path}",
        "description": op.description or op.summary or "",
        "http_method": op.http_method.upper(),
        "source_path": op.source_path,
        "path_template": _path_template(op.source_path),
        "params": [_parameter_context(param) for param in _iter_parameters(op)],
        "request_body_schema": _json_schema(op.request_body),
        "has_request_body": op.request_body is not None,
    }


def _iter_parameters(op: OperationModel) -> list[ParameterModel]:
    return list(itertools.chain(op.path_params, op.query_params, op.header_params, op.cookie_params))


def _parameter_context(param: ParameterModel) -> OperationDict:
    schema = _json_schema(param.schema_model)
    return {
        "name": param.name,
        "location": param.location,
        "required": param.required,
        "description": param.description or f"{param.location} parameter {param.name}",
        "schema": schema,
    }


def _json_schema(schema: SchemaModel | None) -> dict[str, Any]:
    if schema is None:
        return {"type": "string"}
    raw = dict(schema.raw_schema)
    if raw:
        return raw
    rendered: dict[str, Any] = {}
    if schema.type is not None:
        rendered["type"] = schema.type
    if schema.description is not None:
        rendered["description"] = schema.description
    if schema.enum:
        rendered["enum"] = list(schema.enum)
    if schema.default is not None:
        rendered["default"] = schema.default
    if schema.required:
        rendered["required"] = list(schema.required)
    if schema.properties:
        rendered["properties"] = {name: _json_schema(child) for name, child in schema.properties.items()}
    if schema.items is not None:
        rendered["items"] = _json_schema(schema.items)
    return rendered or {"type": "string"}


def _path_template(path: str) -> str:
    """Convert an OpenAPI path template to a TypeScript template-literal fragment.

    Path parameter names are sanitized before interpolation to prevent injection
    of arbitrary identifiers into generated TypeScript code.
    """

    def _replace(match: re.Match[str]) -> str:
        raw_name = match.group(1)
        safe_name = _sanitize_identifier(raw_name)
        if not _TS_IDENTIFIER_RE.match(safe_name):
            # Fallback: the name cannot be made into a valid TS identifier;
            # use a generic placeholder that won't break compilation.
            safe_name = "pathParam"
        return f"${{encodeURIComponent(String(args.{safe_name}))}}"

    return re.sub(r"{([^}]+)}", _replace, path)


def _sanitize_identifier(value: str) -> str:
    """Normalise an arbitrary string to a safe snake_case identifier."""
    stripped = _IDENTIFIER_PATTERN.sub("_", value.strip().lower())
    collapsed = re.sub(r"_+", "_", stripped).strip("_")
    return collapsed or "default"
